// Contenuto della GUIDA in-app (trilingue IT/EN/RU). Si aggiorna a ogni release: aggiornare le sezioni
// quando cambiano le funzioni e aggiungere in NEWS le novità della versione corrente.

type Loc = { t: string; b: string };
export type GuideSection = {
  icon: string; // nome icona Heroicon (vedi components/Icon.tsx)
  shot?: string; // base del nome screenshot in public/manual/<shot>.<lang>.png (auto, scripts/capture-manual.mjs)
  it: Loc;
  en: Loc;
  ru?: Loc; // russo opzionale: finché manca, l'app ripiega sull'inglese
};

export const GUIDE: GuideSection[] = [
  {
    icon: "list",
    shot: "hotels",
    it: { t: "Hotel — sfoglia e cerca", b: "La vista «Hotel» mostra l'archivio. «Per paese»: apri un paese (es. Austria) e vedi i suoi hotel, caricati su richiesta dall'intero database. «Elenco»: lista piatta ordinata per voto o valore atteso, con ricerca per nome/città/regione. Il colore del voto è una scala continua: più caldo = più adatto alle famiglie. «Valuta family-fit» avvia la valutazione di tutti i non valutati." },
    en: { t: "Hotels — browse and search", b: "The «Hotels» view shows the archive. «By country»: open a country (e.g. Austria) to see its hotels, loaded on demand from the whole database. «List»: a flat list sorted by score or expected value, with name/city/region search. The score color is a continuous scale: warmer = more family-friendly. «Score family-fit» runs scoring on everything unscored." },
    ru: { t: "Отели — просмотр и поиск", b: "Вид «Отели» показывает архив. «По странам»: откройте страну (например, Австрию) и увидите её отели, загружаемые по запросу из всей базы данных. «Список»: плоский перечень, отсортированный по оценке или ожидаемой ценности, с поиском по названию, городу или региону. Цвет оценки — это непрерывная шкала: чем теплее, тем больше отель подходит для семей. Кнопка «Оценить family-fit» запускает оценку всех неоценённых отелей." },
  },
  {
    icon: "signal",
    it: { t: "Scansiona (in Copertura)", b: "In «Copertura», il pannello «Scansiona» trova hotel NUOVI da OpenStreetMap e li aggiunge all'archivio. Funziona ovunque: città, provincia, regione o paese. I paesi enormi (USA, Francia) vanno scansionati per stato/regione o con «Completa 100%». I risultati si guardano poi nella vista «Hotel»." },
    en: { t: "Scan (in Coverage)", b: "In «Coverage», the «Scan» panel finds NEW hotels from OpenStreetMap and adds them. Works anywhere: city, province, region or country. Huge countries (US, France) should be scanned by state/region or via “Complete 100%”. Results are then viewed in «Hotels»." },
    ru: { t: "Сканировать (в «Покрытии»)", b: "В разделе «Покрытие» панель «Сканировать» находит НОВЫЕ отели в OpenStreetMap и добавляет их в архив. Работает где угодно: город, провинция, регион или страна. Огромные страны (США, Франция) следует сканировать по штатам/регионам или с помощью «Завершить 100%». Результаты затем смотрят в виде «Отели»." },
  },
  {
    icon: "sparkles",
    it: { t: "Valutazione family-fit", b: "Assegna a ogni hotel un punteggio 0–100 leggendo il suo sito ufficiale in qualsiasi lingua, con un riconoscitore multilingue a regole — gratis, senza alcuna chiave API. Ogni servizio per famiglie vale solo se accompagnato dalla FRASE citata dal sito e verificata parola per parola. Zero dati inventati. La barra in alto mostra l'avanzamento; «Prova» mostra le citazioni." },
    en: { t: "Family-fit scoring", b: "Gives each hotel a 0–100 score by reading its official website in any language, with a multilingual rule-based recognizer — free, no API key. A family service counts only if backed by the SENTENCE quoted from the site and verified word for word. Nothing invented. The top bar shows progress; “Proof” shows the quotes." },
    ru: { t: "Оценка семейного рейтинга", b: "Присваивает каждому отелю оценку 0–100, считывая его официальный сайт на любом языке с помощью многоязычного распознавателя на основе правил — бесплатно, без какого-либо ключа API. Каждая услуга для семей засчитывается только при наличии ФРАЗЫ, процитированной с сайта и проверенной слово за словом. Никаких выдуманных данных. Полоса вверху показывает ход выполнения; «Доказательство» показывает цитаты." },
  },
  {
    icon: "sparkles",
    it: { t: "Come si calcola il punteggio (metodo)", b: "Il family-fit (0–100) è la SOMMA dei punti dei servizi per famiglie effettivamente TROVATI sul sito ufficiale dell'hotel, in qualsiasi lingua. Un servizio conta SOLO se accompagnato dalla frase del sito che lo dichiara, verificata parola per parola (la vedi in «Prova») — zero dati inventati; nessun sito = punteggio 0. I fattori e il loro peso (su 100): Miniclub / animazione bambini 22 · Strutture per bimbi (piscina, area giochi, parco acquatico) 18 · Camere/suite family 14 · Childcare / baby-sitting 12 · Menù e ristorazione bimbi 10 · Attività per fasce d'età 10 · Sicurezza bambini 8 (+ Recensioni 6, riservato a una conferma futura dalle reviews). Pesano di più i segnali che indicano un hotel PENSATO per le famiglie (un vero miniclub con animatori, strutture dedicate, camere family) rispetto a dotazioni più comuni (menù, sicurezza). Il totale dà il voto: oltre la soglia «family» (predefinita 60) l'hotel ha abbastanza servizi forti da essere davvero adatto. Così, sommando i pesi dei servizi provati, si capisce esattamente perché un hotel arriva a un certo punteggio." },
    en: { t: "How the score is computed (method)", b: "The family-fit (0–100) is the SUM of the points of the family services actually FOUND on the hotel's official website, in any language. A service counts ONLY if backed by the sentence from the site that states it, verified word for word (shown under «Proof») — no invented data; no website = score 0. The factors and their weight (out of 100): Kids club / children's animation 22 · Kids facilities (pool, play area, water park) 18 · Family rooms/suites 14 · Childcare / baby-sitting 12 · Kids dining and menu 10 · Age-appropriate activities 10 · Child safety 8 (+ Reviews 6, reserved for a future confirmation from reviews). Signals that show a hotel BUILT for families (a real kids club with animators, dedicated facilities, family rooms) weigh more than common add-ons (menu, safety). The total is the score: above the «family» threshold (default 60) the hotel has enough strong services to be genuinely suitable. So, by summing the weights of the proven services, you see exactly why a hotel reaches a given score." },
    ru: { t: "Как рассчитывается оценка (методика)", b: "Семейный рейтинг (0–100) — это СУММА баллов за услуги для семей, реально НАЙДЕННЫЕ на официальном сайте отеля, на любом языке. Услуга засчитывается ТОЛЬКО при наличии фразы с сайта, которая её подтверждает, проверенной слово в слово (видна в «Доказательстве») — никаких выдуманных данных; нет сайта = оценка 0. Факторы и их вес (из 100): Мини-клуб / детская анимация 22 · Детская инфраструктура (бассейн, игровая зона, аквапарк) 18 · Семейные номера/люксы 14 · Уход за детьми / няня 12 · Детское меню и питание 10 · Занятия по возрасту 10 · Детская безопасность 8 (+ Отзывы 6, зарезервировано для будущего подтверждения по отзывам). Сигналы о том, что отель СОЗДАН для семей (настоящий мини-клуб с аниматорами, специальная инфраструктура, семейные номера), весят больше, чем распространённые дополнения (меню, безопасность). Сумма даёт оценку: выше порога «семейный» (по умолчанию 60) у отеля достаточно сильных услуг. Так, складывая веса подтверждённых услуг, видно, почему отель набирает именно столько баллов." },
  },
  {
    icon: "chat",
    it: { t: "Recensioni", b: "Importa le recensioni raccolte da Cowork con «Dati ▾ → Importa recensioni» (file JSON: ogni voce ha id=osm_type/osm_id, autore, voto, testo, fonte, data — vedi docs/reviews-sample.json). Compaiono espandendo la riga dell'hotel, con il pulsante «Traduci» per renderle nella lingua dell'app. Il numero di recensioni è mostrato come badge nell'elenco. Re-importando, le recensioni di un hotel vengono sostituite (sempre dati reali, niente inventato)." },
    en: { t: "Reviews", b: "Import reviews collected by Cowork via «Data ▾ → Import reviews» (JSON file: each entry has id=osm_type/osm_id, author, rating, text, source, date — see docs/reviews-sample.json). They appear when you expand a hotel row, with a «Translate» button to render them in the app language. The review count shows as a badge in the list. Re-importing replaces a hotel's reviews (always real data, nothing invented)." },
    ru: { t: "Отзывы", b: "Импортируйте отзывы, собранные через Cowork, с помощью «Данные ▾ → Импорт отзывов» (файл JSON: каждая запись содержит id=osm_type/osm_id, автора, оценку, текст, источник, дату — см. docs/reviews-sample.json). Они появляются при разворачивании строки отеля, с кнопкой «Перевести», которая отображает их на языке приложения. Количество отзывов показано как бейдж в списке. При повторном импорте отзывы отеля заменяются (всегда реальные данные, ничего выдуманного)." },
  },
  {
    icon: "sparkles",
    it: { t: "Stelle (classificazione internazionale)", b: "Accanto al nome compare la classificazione ufficiale a stelle (★1–5) presa da OpenStreetMap, con il bollino «Lusso» per i 5 stelle Superior. È un dato REALE (non inventato): dove OSM non lo riporta, non viene mostrato nulla. È diverso dal voto family-fit: le stelle dicono la categoria dell'hotel, il family-fit dice quanto è adatto alle famiglie. Per riempirle sugli hotel già censiti lancia una volta «node scripts/backfill-stars.mjs»; le nuove scansioni le prendono in automatico." },
    en: { t: "Stars (international classification)", b: "Next to the name you see the official star rating (★1–5) from OpenStreetMap, with a “Luxury” badge for 5-star Superior. It is REAL data (not invented): where OSM doesn't report it, nothing is shown. It differs from the family-fit score: stars tell the hotel category, family-fit tells how family-friendly it is. To fill it for already-scanned hotels run once “node scripts/backfill-stars.mjs”; new scans capture it automatically." },
    ru: { t: "Звёзды (международная классификация)", b: "Рядом с названием отображается официальная классификация по звёздам (★1–5), взятая из OpenStreetMap, с пометкой «Люкс» для отелей 5 звёзд Superior. Это РЕАЛЬНЫЕ данные (не выдуманные): там, где OSM их не указывает, ничего не показывается. Это отличается от оценки семейного рейтинга: звёзды говорят о категории отеля, а семейный рейтинг — насколько он подходит для семей. Чтобы заполнить их для уже добавленных отелей, запустите один раз «node scripts/backfill-stars.mjs»; новые сканирования подхватывают их автоматически." },
  },
  {
    icon: "sparkles",
    it: { t: "Fascia di costo (€ → €€€€€)", b: "Accanto a stelle e voto, un indicatore di quanto è caro l'hotel, da € (economico) a €€€€€ (molto caro) — il classico $ → $$$$$. È COMBINATO: se il sito pubblica una fascia di prezzo (schema.org «priceRange») usiamo quel dato REALE — il tooltip mostra il prezzo a notte stimato e la citazione dal sito (badge più marcato). Altrimenti è una STIMA da dati reali: le stelle ★ e l'indice costo-vita del paese (badge più tenue). Nessun prezzo inventato. È diverso dal «valore atteso» (che misura la redditività come partner, non il prezzo per l'ospite)." },
    en: { t: "Cost range (€ → €€€€€)", b: "Next to stars and score, an indicator of how pricey the hotel is, from € (cheap) to €€€€€ (very expensive) — the classic $ → $$$$$. It is COMBINED: if the site publishes a price range (schema.org «priceRange») we use that REAL data — the tooltip shows the estimated nightly price and the quote from the site (bolder badge). Otherwise it is an ESTIMATE from real signals: the stars ★ and the country's cost-of-living index (fainter badge). No invented prices. It differs from «expected value» (which gauges partner revenue, not the guest's price)." },
    ru: { t: "Уровень цен (€ → €€€€€)", b: "Рядом со звёздами и оценкой — показатель того, насколько дорог отель, от € (дёшево) до €€€€€ (очень дорого) — классические $ → $$$$$. КОМБИНИРОВАННЫЙ: если сайт публикует ценовой диапазон (schema.org «priceRange»), используем эти РЕАЛЬНЫЕ данные — во всплывающей подсказке показаны примерная цена за ночь и цитата с сайта (более яркий бейдж). Иначе это ОЦЕНКА по реальным сигналам: звёзды ★ и индекс стоимости жизни страны (более тусклый бейдж). Никаких выдуманных цен. Это отличается от «ожидаемой ценности» (которая оценивает доход от партнёрства, а не цену для гостя)." },
  },
  {
    icon: "pin",
    shot: "coverage",
    it: { t: "Copertura per paese", b: "Mostra, per ogni paese, quanti hotel hai (Trovati), quanti valutati e quanti family (≥ soglia). «Misura» calcola quanti hotel con nome esistono davvero su OpenStreetMap → il GRADO di copertura reale. «Completa 100%» scansiona il paese regione per regione per riempirlo (anche USA/Francia); puoi fermarlo con «Ferma». «Aggiungi e scansiona»: scegli un PAESE da una lista con ricerca (~190, tutto il mondo) — anche non ancora in archivio — e lo scansioni. «Completa tutti i continenti» copre tutti i paesi del mondo e RIPRENDE dal punto in cui si era fermato («riprende da: …», con «ricomincia da capo»), così a furia di lanciarlo copri tutto." },
    en: { t: "Coverage by country", b: "Shows, per country, how many hotels you have (Found), how many scored and how many family (≥ threshold). “Measure” computes how many named hotels actually exist on OpenStreetMap → the real coverage GRADE. “Complete 100%” scans the country region by region to fill it (even US/France); you can stop it with “Stop”. “Add and scan”: pick a COUNTRY from a searchable list (~190, the whole world) — even one not yet in the archive — and scan it. “Complete all continents” covers every country in the world and RESUMES where it stopped (“resumes from: …”, with “start over”), so by running it repeatedly you cover everything." },
    ru: { t: "Покрытие по странам", b: "Показывает для каждой страны, сколько у вас отелей (Найдено), сколько оценено и сколько семейных (≥ порога). «Измерить» вычисляет, сколько отелей с названием реально существует в OpenStreetMap → СТЕПЕНЬ фактического покрытия. «Завершить 100%» сканирует страну регион за регионом (в том числе США/Франция); остановить можно кнопкой «Остановить». «Добавить и сканировать»: выберите СТРАНУ из списка с поиском (~190, весь мир) — даже которой ещё нет в архиве — и сканируйте её. «Завершить все континенты» охватывает все страны мира и ПРОДОЛЖАЕТ с того места, где остановилось («продолжит с: …», с «начать заново»)." },
  },
  {
    icon: "list",
    shot: "crm",
    it: { t: "CRM · acquisizione partner", b: "Gli hotel contattabili ordinati per VALORE ATTESO, con stato del contatto (da contattare → contattato → ha risposto → in trattativa → partner / rifiutato) e nota. «Scrivi email» genera un'email professionale in inglese, personalizzata con le prove dal sito. L'email è colorata per RECAPITABILITÀ (verde = valida, barrata = non recapitabile): non scrive verso indirizzi che rimbalzerebbero. Stato e note restano nel database e sopravvivono a scansioni e backup." },
    en: { t: "CRM · partner acquisition", b: "Contactable hotels ranked by EXPECTED VALUE, with contact status (to contact → contacted → replied → negotiating → partner / declined) and a note. “Write email” generates a professional English email, personalized with the proof from the site. The email is colored by DELIVERABILITY (green = valid, struck-through = undeliverable): it won't write to addresses that would bounce. Status and notes live in the database and survive scans and backups." },
    ru: { t: "CRM · привлечение партнёров", b: "Отели, которым можно написать, отсортированы по ОЖИДАЕМОЙ ЦЕННОСТИ, с указанием статуса контакта (нужно связаться → связались → ответили → в переговорах → партнёр / отказ) и заметкой. Кнопка «Написать email» создаёт профессиональное письмо на английском, персонализированное с использованием доказательств с сайта. Письмо окрашивается по ДОСТАВЛЯЕМОСТИ (зелёный = действительный, зачёркнутый = недоставляемый): на адреса, которые вернули бы письмо, отправка не выполняется. Статус и заметки хранятся в базе данных и сохраняются после сканирований и резервных копий." },
  },
  {
    icon: "sparkles",
    it: { t: "Valore atteso (redditività)", b: "Stima quanto vale ogni hotel come partner: valore prenotazione × indice paese × commissione% × probabilità-partner × volume, dove probabilità e volume crescono col family-fit. È una STIMA per dare priorità, non un dato verificato. Regola le tre manopole in «Assunzioni del modello» o nelle Impostazioni." },
    en: { t: "Expected value (revenue)", b: "Estimates each hotel's worth as a partner: booking value × country index × commission% × partner-probability × volume, where probability and volume grow with family-fit. It is an ESTIMATE for prioritizing, not verified data. Tune the three knobs in “Model assumptions” or in Settings." },
    ru: { t: "Ожидаемая ценность (доходность)", b: "Оценивает, сколько стоит каждый отель как партнёр: стоимость бронирования × индекс страны × комиссия% × вероятность-партнёрства × объём, где вероятность и объём растут вместе с семейным рейтингом. Это ОЦЕНКА для расстановки приоритетов, а не проверенные данные. Настройте три регулятора в разделе «Допущения модели» или в Настройках." },
  },
  {
    icon: "chart",
    shot: "infographic",
    it: { t: "Infografica stampabile", b: "Genera un cruscotto visivo dai tuoi dati reali: numeri chiave (hotel, valutati, family, contattabili), distribuzione dei punteggi, top paesi per family hotel, copertura per continente, funnel di acquisizione (CRM) e valore atteso totale. Scegli orientamento e quali sezioni includere; «Stampa» la apre nel browser di sistema, dove hai tutte le opzioni (PDF, A4/Lettera, margini). Nessun dato inventato." },
    en: { t: "Printable infographic", b: "Generate a visual dashboard from your real data: key figures (hotels, scored, family, contactable), score distribution, top countries by family hotel, coverage by continent, acquisition funnel (CRM) and total expected value. Choose orientation and which sections to include; “Print” opens it in the system browser, with every option (PDF, A4/Letter, margins). Nothing invented." },
    ru: { t: "Печатная инфографика", b: "Создайте визуальную панель на основе ваших реальных данных: ключевые показатели (отели, оценённые, семейные, доступные для контакта), распределение баллов, лучшие страны по семейным отелям, покрытие по континентам, воронку привлечения (CRM) и общую ожидаемую ценность. Выберите ориентацию и разделы для включения; кнопка «Печать» открывает инфографику в системном браузере, где доступны все опции (PDF, A4/Letter, поля). Никаких вымышленных данных." },
  },
  {
    icon: "download",
    it: { t: "Dati, backup ed esportazione", b: "Esporta/importa l'intero archivio come un singolo file .sqlite (l'unica copia dei tuoi dati: fai backup spesso). «Esporta selezione» compone il gruppo da condividere coi collaboratori scegliendo l'ambito (tutti / un continente / un paese), una fascia di punteggio (es. 59–100) o «le migliori N», più filtri (solo valutati / contattabili / email recapitabile): salvi in CSV (apre in Excel) o in JSON strutturato con le prove citate." },
    en: { t: "Data, backup and export", b: "Export/import the whole archive as a single .sqlite file (the only copy of your data: back up often). “Export selection” composes the group to share with collaborators by choosing the scope (all / a continent / a country), a score range (e.g. 59–100) or “top N”, plus filters (scored / contactable / deliverable email): save to CSV (opens in Excel) or structured JSON with the cited proof." },
    ru: { t: "Данные, резервное копирование и экспорт", b: "Экспортируйте и импортируйте весь архив одним файлом .sqlite (это единственная копия ваших данных — делайте резервные копии часто). «Экспорт выборки» формирует набор для передачи коллегам: вы выбираете охват (все / один континент / одна страна), диапазон баллов (например, 59–100) или «лучшие N», а также фильтры (только оценённые / доступные для контакта / с доставляемым email). Сохранение происходит в CSV (открывается в Excel) или в структурированном JSON с приведёнными доказательствами." },
  },
  {
    icon: "sparkles",
    it: { t: "AI · Cowork", b: "Per superare il tetto delle regole, esporta un lotto di hotel da valutare, falli leggere all'AI (Cowork, col tuo piano Claude — nessuna chiave API) e reimporta i voti con la prova. L'AI legge i siti in ogni lingua e coglie sfumature che le regole non vedono." },
    en: { t: "AI · Cowork", b: "To go beyond the rules' ceiling, export a batch of hotels to score, have the AI read them (Cowork, on your Claude plan — no API key) and re-import the scores with the proof. The AI reads sites in any language and catches nuances the rules miss." },
    ru: { t: "ИИ · Cowork", b: "Чтобы выйти за пределы возможностей правил, экспортируйте партию отелей для оценки, передайте её на чтение ИИ (Cowork, на вашем тарифе Claude — без ключа API) и реимпортируйте оценки вместе с доказательством. ИИ читает сайты на любом языке и улавливает нюансы, которые правила не замечают." },
  },
];

// Novità della versione corrente (aggiornare a ogni release). Mostrate in cima alla Guida.
export const NEWS: { it: string; en: string; ru?: string }[] = [
  { it: "**Lista paesi completa** — la lista mondiale passa da 193 a **207 paesi**: aggiunti i 14 che mancavano (Ciad, Yemen, Siria, Eritrea, Sud Sudan, Rep. Centrafricana, Guinea Equatoriale, Guinea-Bissau, São Tomé e Príncipe, Corea del Nord, Micronesia, Isole Marshall, Nauru, Tuvalu). «Completa tutti» e il selettore «Aggiungi paese» ora coprono davvero tutto il mondo.", en: "**Complete country list** — the world list goes from 193 to **207 countries**: added the 14 that were missing (Chad, Yemen, Syria, Eritrea, South Sudan, Central African Republic, Equatorial Guinea, Guinea-Bissau, São Tomé and Príncipe, North Korea, Micronesia, Marshall Islands, Nauru, Tuvalu). «Complete all» and the «Add country» picker now truly cover the whole world.", ru: "**Полный список стран** — мировой список вырос с 193 до **207 стран**: добавлены 14 недостающих (Чад, Йемен, Сирия, Эритрея, Южный Судан, ЦАР, Экваториальная Гвинея, Гвинея-Бисау, Сан-Томе и Принсипи, КНДР, Микронезия, Маршалловы Острова, Науру, Тувалу). «Сканировать всё» и выбор «Добавить страну» теперь действительно охватывают весь мир.", },
  { it: "**Più dati a costo zero** — ogni scansione di OpenStreetMap già scaricava molti tag che buttavamo: ora salviamo quelli utili (**accessibilità** wheelchair, **wifi**, **piscina**, **catena** brand/operator, **orari/stagionalità**, indirizzo completo) nel campo `osm_attrs`. Nessuna richiesta di rete in più: è dato già in casa, dato reale OSM. Si popola alle prossime scansioni e alimenterà nuove dimensioni del report di mercato e l'esclusione delle catene.", en: "**More data at zero cost** — every OpenStreetMap scan already downloaded many tags we were throwing away: we now keep the useful ones (**accessibility** wheelchair, **wifi**, **swimming pool**, **chain** brand/operator, **hours/seasonality**, full address) in the `osm_attrs` field. No extra network request: it's data already in hand, real OSM data. It populates on the next scans and will feed new market-report dimensions and chain exclusion.", ru: "**Больше данных бесплатно** — каждое сканирование OpenStreetMap уже скачивало множество тегов, которые мы выбрасывали: теперь сохраняем полезные (**доступность** wheelchair, **wifi**, **бассейн**, **сеть** brand/operator, **часы/сезонность**, полный адрес) в поле `osm_attrs`. Без дополнительных сетевых запросов: это уже имеющиеся реальные данные OSM. Заполняется при следующих сканированиях и будет питать новые измерения отчёта о рынке и исключение сетей.", },
  { it: "**Punteggio più credibile** — il motore ora riconosce le **frasi di esclusione**: «adults only, niente kids club» non fa più scattare per sbaglio il segnale «kids club». E se il sito dichiara l'hotel **solo adulti** (adults only, child-free, couples only, in 6 lingue) il family-fit viene **azzerato** con un flag «Solo adulti» e la prova citata. Chiude il falso positivo più grave che minava certificati, report e analytics. Pattern curati in `signals.json`, due test automatici.", en: "**More credible score** — the engine now recognises **exclusion phrases**: «adults only, no kids club» no longer wrongly triggers the «kids club» signal. And if the site declares the hotel **adults-only** (adults only, child-free, couples only, across 6 languages) the family-fit is **set to zero** with an «Adults only» flag and the quoted proof. Closes the worst false positive that undermined certificates, reports and analytics. Curated patterns in `signals.json`, two automated tests.", ru: "**Более достоверный балл** — движок теперь распознаёт **фразы-исключения**: «adults only, no kids club» больше не вызывает ошибочно сигнал «детский клуб». А если сайт заявляет, что отель **только для взрослых** (adults only, child-free, couples only, на 6 языках), family-fit **обнуляется** с флагом «Только для взрослых» и процитированным доказательством. Закрывает самый серьёзный ложный позитив, подрывавший сертификаты, отчёты и аналитику. Выверенные паттерны в `signals.json`, два автотеста.", },
  { it: "**Family-Fit as a Service** (menu Dati → «Valuta un hotel su richiesta») — incolli il **sito di un qualsiasi hotel** e Radar applica lo **stesso punteggio family-fit** dell'archivio, restituendo il risultato con la **prova citata dal sito** e la **risposta in formato API (JSON)**. **Il database Kidotel non viene toccato**: si valuta solo il sito fornito, il dato resta del cliente. Dimostra la metodologia/scoring come servizio (via economica: il cliente porta i suoi hotel, riceve lo score).", en: "**Family-Fit as a Service** (Data menu → «Score a hotel on demand») — paste **any hotel's website** and Radar applies the **same family-fit score** as the archive, returning the result with the **proof quoted from the site** and the **API-shaped response (JSON)**. **The Kidotel database is not touched**: only the provided site is scored, the data stays the client's. Demonstrates the methodology/scoring as a service (revenue line: the client brings their hotels, gets the score).", ru: "**Family-Fit as a Service** (меню Данные → «Оценить отель по запросу») — вставьте **сайт любого отеля**, и Radar применяет **тот же балл family-fit**, что и для архива, возвращая результат с **доказательством, процитированным с сайта**, и **ответом в формате API (JSON)**. **База данных Kidotel не затрагивается**: оценивается только предоставленный сайт, данные остаются у клиента. Демонстрирует методологию/скоринг как сервис (направление дохода: клиент приносит свои отели, получает балл).", },
  { it: "**Analisi premium** — nella riga di un hotel valutato (espandi → «Analisi premium») un report che trasforma il punteggio in **insight azionabile**: il **percentile** vs i concorrenti nel mondo (es. «Top 8%»), il **benchmark del paese**, **da dove arriva il punteggio** (quali segnali presenti/mancanti e con che peso) e le **leve di miglioramento** (i segnali mancanti pesati: «+10 comunicando X»). È un Produced Work con attribuzione OSM, nessun dato di altri hotel identificabile. Abilita la via economica «analytics premium» per l'hotel.", en: "**Premium analytics** — on a scored hotel's row (expand → «Premium analytics») a report that turns the score into **actionable insight**: the **percentile** vs competitors worldwide (e.g. «Top 8%»), the **country benchmark**, **where the score comes from** (which signals present/missing and with what weight) and the **improvement levers** (the missing signals, weighted: «+10 by stating X»). It's a Produced Work with OSM attribution, no other hotel identifiable. Enables the «premium analytics» revenue line for the hotel.", ru: "**Премиум-аналитика** — в строке оценённого отеля (разверните → «Премиум-аналитика») отчёт, превращающий балл в **действенные инсайты**: **процентиль** vs конкуренты в мире (напр. «Топ 8%»), **бенчмарк страны**, **откуда берётся балл** (какие сигналы есть/нет и с каким весом) и **рычаги улучшения** (отсутствующие сигналы по весу: «+10, указав X»). Это Produced Work с атрибуцией OSM, другие отели не идентифицируемы. Включает направление дохода «премиум-аналитика» для отеля.", },
  { it: "**Kidotel Certified** — nella riga di un hotel valutato (espandi → «Certificato Kidotel») generi un **certificato brandizzato** con punteggio + i servizi famiglia e la **prova citata dal sito** (con fonte), da inviare/stampare per l'hotel; e viene **copiato negli appunti un badge** che l'hotel incolla sul suo sito (link a kidotel.co → backlink). È un'opera derivata (Produced Work) con attribuzione OpenStreetMap. Abilita la via economica «Kidotel Certified» (l'hotel paga audit/badge).", en: "**Kidotel Certified** — on a scored hotel's row (expand → «Kidotel certificate») you generate a **branded certificate** with the score + family services and the **proof quoted from the site** (with source), to send/print for the hotel; and a **badge is copied to the clipboard** for the hotel to paste on its website (links to kidotel.co → backlink). It's a Produced Work with OpenStreetMap attribution. Enables the «Kidotel Certified» revenue line (the hotel pays for the audit/badge).", ru: "**Kidotel Certified** — в строке оценённого отеля (разверните → «Сертификат Kidotel») создаётся **фирменный сертификат** с баллом, семейными услугами и **доказательством, процитированным с сайта** (с источником), для отправки/печати отелю; а в буфер обмена **копируется бейдж** для вставки на сайт отеля (ссылка на kidotel.co → бэклинк). Это Produced Work с атрибуцией OpenStreetMap. Включает направление дохода «Kidotel Certified» (отель платит за аудит/бейдж).", },
  { it: "Monetizzazione «da fare ora» #2 — **Report di mercato** (menu Dati → «Report insight»): un documento HTML stampabile con SOLO statistiche **aggregate** (hotel analizzati, quota family, distribuzione punteggi, migliori destinazioni, copertura per continente). È un'opera derivata (Produced Work) con attribuzione OpenStreetMap: **vendibile/condivisibile**, niente schede-hotel né dati interni (CRM/valore). La «da fare ora» #1 (contenuti/classifiche SEO) è già coperta dal Feed sito.", en: "Monetisation «do now» #2 — **Market report** (Data menu → «Insights report»): a printable HTML document with ONLY **aggregated** statistics (hotels analysed, family share, score distribution, top destinations, coverage by continent). It's a Produced Work with OpenStreetMap attribution: **sellable/shareable**, no hotel records nor internal data (CRM/value). «Do now» #1 (SEO content/rankings) is already covered by the Site feed.", ru: "Монетизация «сделать сейчас» #2 — **Отчёт о рынке** (меню Данные → «Отчёт-инсайт»): печатный HTML-документ ТОЛЬКО с **агрегированной** статистикой (проанализировано отелей, доля семейных, распределение баллов, топ направлений, охват по континентам). Это Produced Work с атрибуцией OpenStreetMap: **для продажи/передачи**, без карточек отелей и внутренних данных (CRM/ценность). «Сделать сейчас» #1 (SEO-контент/рейтинги) уже покрыт Фидом сайта." },
  { it: "Verso kidotel.co (Fase 1): nuovo export «Feed sito» nell'export a criteri — un JSON «Produced Work» con identità, punteggio, fatti family, UNA prova breve attribuita con la fonte, fascia prezzo come «stima Kidotel» e un link «rivendica la scheda» per ogni hotel (niente contatti privati). In Impostazioni → «Integrazione kidotel.co» imposti la base del link di claim e l'eventuale ID affiliato Booking. Le email di outreach del CRM ora sono trilingui (IT/EN/RU, seguono la lingua dell'app) e includono il link di claim.", en: "Towards kidotel.co (Phase 1): new «Site feed» export in the criteria export — a «Produced Work» JSON with identity, score, family facts, ONE short attributed proof with its source, price tier as a «Kidotel estimate» and a «claim your listing» link per hotel (no private contacts). In Settings → «kidotel.co integration» you set the claim-link base and an optional Booking affiliate ID. CRM outreach emails are now trilingual (IT/EN/RU, following the app language) and include the claim link.", ru: "В сторону kidotel.co (Этап 1): новый экспорт «Фид сайта» в экспорте по критериям — JSON «Produced Work» с идентификацией, баллом, семейными фактами, ОДНИМ кратким доказательством с источником, ценовой категорией как «оценка Kidotel» и ссылкой «активируйте профиль» для каждого отеля (без приватных контактов). В Настройках → «Интеграция с kidotel.co» задаются база ссылки активации и необязательный партнёрский ID Booking. Письма CRM теперь трёхъязычные (IT/EN/RU, по языку приложения) и включают ссылку активации." },
  { it: "«Apri l'hotel» — espandi la riga di un hotel (o nel CRM) per raggiungerlo: Sito ufficiale (atterra esattamente sull'hotel), Cerca (DuckDuckGo, mette il sito #1), Booking (hotel come primo risultato + prezzi), Mappa (OpenStreetMap, pin esatto). Scelti dopo verifica live: tutti consent-free. Tolti Google Hotels/Maps (da IT/UE google.com forza il muro cookie «Prima di continuare» prima di mostrare l'hotel) ed Expedia/Hotels.com (la scheda richiede il loro hotel-id interno, non derivabile dai dati): arriveranno con le affiliazioni (roadmap).", en: "«Open the hotel» — expand a hotel row (or in the CRM) to reach it: Website (lands exactly on the hotel), Search (DuckDuckGo, ranks the site #1), Booking (hotel as top result + prices), Map (OpenStreetMap, exact pin). Chosen after live testing: all consent-free. Dropped Google Hotels/Maps (from IT/EU google.com forces the «Before you continue» cookie wall before showing the hotel) and Expedia/Hotels.com (their page needs their internal hotel-id, not derivable from our data): they'll come with the affiliations (roadmap).", ru: "«Открыть отель» — разверните строку отеля (или в CRM), чтобы перейти к нему: Сайт (ведёт точно на отель), Поиск (DuckDuckGo, ставит сайт на #1), Booking (отель как первый результат + цены), Карта (OpenStreetMap, точная метка). Выбрано после реальной проверки: всё без cookie-стен. Убрали Google Hotels/Maps (из IT/ЕС google.com показывает «Прежде чем продолжить» до отеля) и Expedia/Hotels.com (их страница требует внутренний hotel-id, не выводимый из наших данных): появятся с партнёрками (планы)." },
  { it: "Scansione del mondo a RIPRESA: «Completa tutti» ora copre TUTTI i paesi del mondo (non solo quelli già in archivio) e RIPRENDE dal punto in cui si era fermato, invece di ricominciare ogni volta dall'Europa. In «Copertura» vedi «riprende da: <paese>» e puoi «ricominciare da capo».", en: "RESUMABLE world scan: «Complete all» now covers EVERY country in the world (not just those already in the archive) and RESUMES where it stopped, instead of restarting from Europe each time. In «Coverage» you see «resumes from: <country>» and can «start over».", ru: "ВОЗОБНОВЛЯЕМОЕ сканирование мира: «Завершить все» теперь охватывает ВСЕ страны мира (не только уже в архиве) и ПРОДОЛЖАЕТ с того места, где остановилось, а не начинает каждый раз с Европы. В «Покрытии» видно «продолжит с: <страна>» и можно «начать заново»." },
  { it: "Nuovo: aggiungi un PAESE da una lista con ricerca (in «Copertura») — anche paesi non ancora in archivio (tutto il mondo, ~190 paesi) — e scansionalo con un clic.", en: "New: add a COUNTRY from a searchable list (in «Coverage») — even countries not yet in the archive (the whole world, ~190 countries) — and scan it with one click.", ru: "Новое: добавьте СТРАНУ из списка с поиском (в «Покрытии») — даже страны, которых ещё нет в архиве (весь мир, ~190 стран) — и сканируйте её одним щелчком." },
  { it: "Nuovo: fascia di costo da € a €€€€€ (il classico $→$$$$$) per ogni hotel. Quanto è caro: se il sito pubblica una fascia di prezzo (schema.org) usiamo quel dato REALE (con la prova nel tooltip), altrimenti una STIMA da stelle ★ e paese (badge più tenue). Nessun prezzo inventato.", en: "New: cost range from € to €€€€€ (the classic $→$$$$$) per hotel. How pricey it is: if the site publishes a price range (schema.org) we use that REAL data (with the proof in the tooltip), otherwise an ESTIMATE from stars ★ and country (fainter badge). No invented prices.", ru: "Новое: уровень цен от € до €€€€€ (классические $→$$$$$) для каждого отеля. Насколько дорого: если сайт публикует ценовой диапазон (schema.org), используем эти РЕАЛЬНЫЕ данные (с доказательством во всплывающей подсказке), иначе ОЦЕНКА по звёздам ★ и стране (более тусклый бейдж). Никаких выдуманных цен." },
  { it: "Scansione stelle più veloce: la classificazione ★ (da OSM) ora scarica in parallelo a blocchi più grandi (≈3× più rapida, client condiviso). I blocchi falliti vengono ritentati invece di marcare gli hotel come «senza stelle».", en: "Faster star scan: the ★ classification (from OSM) now downloads in parallel in bigger batches (~3× faster, shared client). Failed batches are retried instead of marking hotels as “no stars”.", ru: "Быстрее сканирование звёзд: классификация ★ (из OSM) теперь загружается параллельно бо́льшими блоками (≈ в 3 раза быстрее, общий клиент). Неудавшиеся блоки повторяются, а не помечают отели как «без звёзд»." },
  { it: "Manuale completo in russo: la Guida integrata è ora interamente tradotta (italiano, inglese e russo) e allineata ai nomi reali dei pulsanti dell'app.", en: "Full Russian manual: the in-app Guide is now entirely translated (Italian, English and Russian) and aligned with the app's real button names.", ru: "Полное руководство на русском: встроенная Справка теперь полностью переведена (итальянский, английский и русский) и согласована с реальными названиями кнопок приложения." },
  { it: "Recensioni per hotel: importa le reviews raccolte da Cowork (Dati ▾ → Importa recensioni, formato JSON). Compaiono espandendo la riga, con voto/autore/fonte e il pulsante «Traduci». Badge col numero nell'elenco.", en: "Per-hotel reviews: import reviews collected by Cowork (Data ▾ → Import reviews, JSON). They appear when you expand a row, with rating/author/source and a «Translate» button. Count badge in the list.", ru: "Отзывы по отелям: импорт отзывов, собранных Cowork (Данные ▾ → Импорт отзывов, JSON). Видны при раскрытии строки, с оценкой/автором/источником и кнопкой «Перевести»." },
  { it: "Traduzione automatica delle prove: sotto ogni citazione c'è «Traduci» che la rende nella lingua dell'app (IT/EN/RU). L'originale verbatim resta sempre visibile.", en: "Automatic proof translation: under each quote a «Translate» button renders it in the app language (IT/EN/RU). The verbatim original stays visible.", ru: "Автоперевод доказательств: под каждой цитатой кнопка «Перевести» на язык приложения (IT/EN/RU). Оригинал всегда виден." },
  { it: "CRM più mirato: filtri per concentrarti sui prospect più redditizi (paese, stelle ★, family-fit, valore atteso minimo, solo email recapitabile) + il valore atteso totale del gruppo selezionato.", en: "Sharper CRM: filters to focus on the most profitable prospects (country, stars ★, family-fit, min expected value, deliverable email only) + the total expected value of the selected group.", ru: "Точнее CRM: фильтры по самым выгодным (страна, звёзды ★, family-fit, мин. ожидаемая ценность, только доставляемый email) + суммарная ожидаемая ценность выборки." },
  { it: "Paginazione: l'elenco dell'archivio ora si sfoglia a pagine (5000 per pagina, «pagina i di N»), non più solo i primi 5000.", en: "Pagination: the archive list is now paged (5000 per page, «page i of N»), no longer just the first 5000.", ru: "Постраничный просмотр архива (5000 на страницу, «страница i из N»)." },
  { it: "Scansione INCREMENTALE: «Completa» salta le regioni già scansionate negli ultimi 30 giorni → riprese rapide, non riparte da capo. Nuovo «Completa tutti i continenti».", en: "INCREMENTAL scan: «Complete» skips regions scanned in the last 30 days → fast resumes, no restart from scratch. New «Complete all continents».", ru: "ИНКРЕМЕНТНОЕ сканирование: «Завершить» пропускает регионы, просканированные за последние 30 дней → быстрые возобновления. Новое «Завершить все континенты»." },
  { it: "Nuovo: «Assegna stelle (da OSM)» in Copertura — ri-scansiona il database per la classificazione a stelle, direttamente dall'app. E la misura di copertura ora si SALVA (non si perde più chiudendo).", en: "New: «Assign stars (from OSM)» in Coverage — re-scan the database for the star rating, right from the app. And the coverage measurement is now SAVED (no longer lost on close).", ru: "Новое: «Присвоить звёзды (из OSM)» в «Покрытии». И измерение покрытия теперь СОХРАНЯЕТСЯ." },
  { it: "Nuova lingua: RUSSO. L'interfaccia è ora disponibile in italiano, inglese e russo (selettore in alto IT·EN·RU).", en: "New language: RUSSIAN. The interface is now available in Italian, English and Russian (IT·EN·RU switch at the top).", ru: "Новый язык: РУССКИЙ. Интерфейс теперь доступен на итальянском, английском и русском (переключатель IT·EN·RU вверху)." },
  { it: "Nuovo: classificazione internazionale a stelle (★1–5 + «Lusso») per ogni hotel, presa da OpenStreetMap dove disponibile. Per riempirla sugli hotel già in archivio: «node scripts/backfill-stars.mjs».", en: "New: international star rating (★1–5 + “Luxury”) per hotel, taken from OpenStreetMap where available. To fill it for hotels already in the archive: “node scripts/backfill-stars.mjs”.", ru: "Новое: международная классификация по звёздам (★1–5 + «Люкс») для каждого отеля, взятая из OpenStreetMap, где доступно. Чтобы заполнить её для отелей, уже находящихся в архиве: «node scripts/backfill-stars.mjs»." },
  { it: "Mappa: risolto il «rimbalzo» — ora resta dove la sposti/zoomi.", en: "Map: fixed the “snap-back” — it now stays where you pan/zoom it.", ru: "Карта: устранён «отскок» — теперь она остаётся там, куда вы её переместили или приблизили." },
  { it: "Risolto lo stallo della valutazione: era un errore di lettura di certe pagine (siti con caratteri speciali) che bloccava la coda. Ora la valutazione gira in blocchi paralleli, veloce e senza fermarsi (~14.000 hotel/ora).", en: "Fixed the scoring stall: a parsing error on some pages (sites with special characters) was freezing the queue. Scoring now runs in parallel batches, fast and without stopping (~14,000 hotels/hour).", ru: "Устранено зависание оценки: причиной была ошибка чтения некоторых страниц (сайты со специальными символами), которая блокировала очередь. Теперь оценка выполняется параллельными блоками, быстро и без остановок (~14.000 отелей/час)." },
  { it: "Interfaccia riorganizzata: barra dei menu in alto (Hotel · Mappa · Copertura · CRM · Infografica · Dati), niente più colonna laterale. La scansione vive in Copertura; Backup/Export/AI sotto il menu «Dati».", en: "Reorganized interface: top menu bar (Hotels · Map · Coverage · CRM · Infographic · Data), no more sidebar. Scanning lives in Coverage; Backup/Export/AI under the «Data» menu.", ru: "Переработан интерфейс: панель меню сверху (Отели · Карта · Покрытие · CRM · Инфографика · Данные), боковой колонки больше нет. Сканирование находится в разделе «Покрытие»; Резервное копирование/Экспорт/AI — в меню «Данные»." },
  { it: "Nuovo: sfoglia gli hotel per paese — apri «Austria» e vedi la lista dei suoi hotel (caricata su richiesta dall'intero archivio). In alternativa, l'elenco piatto ordinato per voto/valore con la ricerca per nome.", en: "New: browse hotels by country — open «Austria» to see its hotels (loaded on demand from the whole archive). Or the flat list sorted by score/value with name search.", ru: "Новое: просматривайте отели по странам — откройте «Австрия» и увидите список её отелей (загружается по запросу из всего архива). Либо плоский список, отсортированный по оценке/ценности, с поиском по названию." },
  { it: "Punteggi più leggibili: il colore del voto ora è una scala continua (grigio sotto soglia → pesca → ambra profonda), così la differenza tra un 64 e un 88 si vede a colpo d'occhio.", en: "More readable scores: the badge color is now a continuous scale (grey below threshold → peach → deep amber), so the difference between a 64 and an 88 is visible at a glance.", ru: "Оценки стали понятнее: цвет оценки теперь представляет собой непрерывную шкалу (серый ниже порога → персиковый → глубокий янтарный), так что разницу между 64 и 88 видно с первого взгляда." },
  { it: "Valutazione più fluida: niente più stalli su siti lenti — client web condiviso, timeout più corti, tetto di 16s per hotel e avanzamento aggiornato in continuo.", en: "Smoother scoring: no more stalls on slow sites — shared web client, shorter timeouts, a 16s per-hotel cap and continuously updated progress.", ru: "Более плавная оценка: больше никаких зависаний на медленных сайтах — общий веб-клиент, более короткие тайм-ауты, лимит 16 с на отель и непрерывно обновляемый прогресс." },
  { it: "Nuova veste grafica: adottati logo, colori e caratteri ufficiali Kidotel (wordmark con la scia radar, palette pesca/ambra su grigio, font Sora + Manrope). Coerente in app, infografica e report.", en: "New look: official Kidotel logo, colors and fonts adopted (radar-sweep wordmark, peach/amber on grey, Sora + Manrope). Consistent across app, infographic and report.", ru: "Новое оформление: приняты официальные логотип, цвета и шрифты Kidotel (вордмарк с радарным шлейфом, персиково-янтарная палитра на сером, шрифты Sora + Manrope). Единообразно в приложении, инфографике и отчётах." },
  { it: "Nuovo: «Infografica» — un cruscotto stampabile dai tuoi dati reali (numeri chiave, distribuzione dei punteggi, top paesi, copertura per continente, funnel CRM, valore atteso) con anteprima e stampa/PDF dal browser.", en: "New: “Infographic” — a printable dashboard from your real data (key figures, score distribution, top countries, coverage by continent, CRM funnel, expected value) with preview and print/PDF from the browser.", ru: "Новое: «Инфографика» — печатная панель на основе ваших реальных данных (ключевые числа, распределение оценок, топ стран, покрытие по континентам, воронка CRM, ожидаемая ценность) с предпросмотром и печатью/PDF из браузера." },
  { it: "Nuovo: «Esporta selezione» — componi il gruppo di hotel da condividere (tutti / un continente / un paese, fascia di punteggio, le migliori N, solo contattabili) ed esporta in CSV o JSON.", en: "New: “Export selection” — compose the group of hotels to share (all / a continent / a country, score range, top N, contactable only) and export to CSV or JSON.", ru: "Новое: «Экспорт выборки» — соберите группу отелей для обмена (все / континент / страна, диапазон оценок, лучшие N, только с контактами) и экспортируйте в CSV или JSON." },
  { it: "Revisione completa (qualità): la soglia «family hotel» delle Impostazioni ora vale ovunque — tabella, CRM, mappa e Copertura mostrano lo stesso criterio.", en: "Full audit (quality): the “family hotel” threshold in Settings now applies everywhere — table, CRM, map and Coverage all share the same cut-off.", ru: "Полный пересмотр (качество): порог «семейный отель» из Настроек теперь действует везде — таблица, CRM, карта и Покрытие показывают один и тот же критерий." },
  { it: "Correzioni: importazione backup più sicura (niente dati vecchi residui), conteggi Copertura senza doppioni «(sconosciuto)», estrazione email più precisa, note CRM sempre allineate.", en: "Fixes: safer backup import (no leftover stale data), Coverage counts without duplicate “(unknown)” rows, more accurate email extraction, CRM notes always in sync.", ru: "Исправления: более надёжный импорт резервной копии (без остатков старых данных), подсчёты Покрытия без дублей «(неизвестно)», более точное извлечение email, заметки CRM всегда согласованы." },
  { it: "Copertura per paese: «Misura» (grado reale vs OpenStreetMap) e «Completa 100%» (scansione regione per regione, anche per i paesi enormi).", en: "Coverage by country: “Measure” (real grade vs OpenStreetMap) and “Complete 100%” (region-by-region scan, even for huge countries).", ru: "Покрытие по странам: «Измерить» (реальная степень против OpenStreetMap) и «Завершить 100%» (сканирование регион за регионом, даже для огромных стран)." },
  { it: "Email: verifica di recapitabilità (MX/DNS) e generazione di email di contatto professionali in inglese, personalizzate con le prove.", en: "Email: deliverability check (MX/DNS) and generation of professional English outreach emails, personalized with the proof.", ru: "Email: проверка доставляемости (MX/DNS) и генерация профессиональных контактных писем на английском, персонализированных с доказательствами." },
  { it: "Prestazioni e sicurezza: database più veloce (WAL + indici), backup versionato, pulizia delle catene.", en: "Performance & safety: faster database (WAL + indexes), versioned backup, chain cleanup.", ru: "Производительность и безопасность: более быстрая база данных (WAL + индексы), версионированное резервное копирование, очистка цепочек." },
  { it: "Nuovo: Guida integrata e Impostazioni.", en: "New: in-app Guide and Settings.", ru: "Новое: встроенное Руководство и Настройки." },
];
